### ISSUE TITLE
Use trait Identifier and create trait for variables created, updated

### ISSUE THREAD

**Issue by MartkCz** [ThunboltCMS/cms#3]

**Comment by jelen07** [comment]
Přesně tenhle issue mám i u sebe. Pro Identifier používám 
`use \Kdyby\Doctrine\Entities\Attributes\Identifier;`
U traity pro created a updated jsem narazil na problém, kdy v konstruktoru traity jsem nastavoval aktuální čas pro created, a pak v dané entitě je potřeba nastavit v konstruktoru jiné výchozí hodoty. Tak se to mezi sebou bilo 😞

**Comment by MartkCz** [comment]
Pro identifikátor použiji také traitu od kdyby. Pro proměnné created, updated tohle: https://github.com/Zenify/DoctrineBehaviors#timestampable , ale ještě jsem to neodzkoušel.

Pokud používáš gedmo anotaci, tak se časy automaticky nastavují, takže žádné nastavování v konstruktoru ani v lifecycleEventech
